# Generated by Django 4.2.7 on 2025-08-20 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code permission')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la permission')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('sales', 'Ventes'), ('products', 'Produits'), ('stocks', 'Stocks'), ('tables', 'Tables'), ('orders', 'Commandes'), ('kitchen', 'Cuisine'), ('reports', 'Rapports'), ('analytics', 'Analyses'), ('users', 'Utilisateurs'), ('suppliers', 'Fournisseurs'), ('expenses', 'Dépenses'), ('settings', 'Paramètres')], max_length=20, verbose_name='Catégorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Permission active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('server', 'Serveur'), ('cashier', 'Caissier')], default='server', max_length=20, verbose_name='Rôle'),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'attribution")),
                ('is_active', models.BooleanField(default=True, verbose_name='Permission active')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Accordée par')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.permission', verbose_name='Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Permission utilisateur',
                'verbose_name_plural': 'Permissions utilisateurs',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
