# Generated by Django 4.2.7 on 2025-08-18 09:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0002_product_shelf_life_days_product_storage_temperature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('proteins', 'Protéines'), ('vegetables', 'Légumes'), ('grains', 'Céréales'), ('dairy', 'Produits laitiers'), ('spices', 'Épices'), ('beverages_base', 'Base boissons'), ('alcohol', 'Alcool'), ('condiments', 'Condiments')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Catégorie d'ingrédient",
                'verbose_name_plural': "Catégories d'ingrédients",
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('beverages', 'Boissons'), ('hot_drinks', 'Boissons chaudes'), ('cocktails', 'Cocktails'), ('appetizers', 'Entrées'), ('main_courses', 'Plats principaux'), ('desserts', 'Desserts'), ('snacks', 'Snacks')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de menu',
                'verbose_name_plural': 'Catégories de menu',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(help_text='Instructions de préparation')),
                ('prep_time', models.PositiveIntegerField(help_text='Temps de préparation en minutes')),
                ('cook_time', models.PositiveIntegerField(default=0, help_text='Temps de cuisson en minutes')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10)),
                ('portions', models.PositiveIntegerField(default=1, help_text='Nombre de portions produites')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('simple', 'Produit simple'), ('recipe', 'Basé sur recette'), ('combo', 'Menu combo')], max_length=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('direct_stock', models.DecimalField(decimal_places=3, default=0, help_text='Stock direct (pour boissons, snacks...)', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.menucategory')),
                ('recipe', models.ForeignKey(blank=True, help_text='Recette associée (pour les plats cuisinés)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.recipe')),
            ],
            options={
                'verbose_name': 'Article du menu',
                'verbose_name_plural': 'Articles du menu',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogrammes'), ('g', 'Grammes'), ('l', 'Litres'), ('ml', 'Millilitres'), ('pieces', 'Pièces'), ('cups', 'Tasses'), ('tbsp', 'Cuillères à soupe'), ('tsp', 'Cuillères à café')], max_length=10)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Coût par unité en BIF', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredientcategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='products.recipe')),
            ],
            options={
                'verbose_name': 'Ingrédient de recette',
                'verbose_name_plural': 'Ingrédients de recette',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
