# Generated by Django 4.2.7 on 2025-08-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0003_enhanced_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_ingredients', to='suppliers.supplier'),
        ),
    ]
