# Generated by Django 4.2.7 on 2025-08-15 11:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_ratio', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text="Quantité de substitut nécessaire pour 1 unité d'original", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Ratio de conversion')),
                ('priority', models.PositiveIntegerField(default=1, help_text='1 = priorité la plus haute', verbose_name='Priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Substitution active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes sur la substitution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('original_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='kitchen.ingredient', verbose_name='Ingrédient original')),
                ('substitute_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_for', to='kitchen.ingredient', verbose_name='Ingrédient de substitution')),
            ],
            options={
                'verbose_name': "Substitution d'ingrédient",
                'verbose_name_plural': "Substitutions d'ingrédients",
                'ordering': ['original_ingredient', 'priority'],
                'unique_together': {('original_ingredient', 'substitute_ingredient')},
            },
        ),
    ]
