# Generated by Django 4.2.7 on 2025-08-17 06:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0002_ingredientsubstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePreparationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_prepared', models.PositiveIntegerField(verbose_name='Quantité préparée')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('rolled_back', 'Annulée (rollback)')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Coût total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_batches', to='kitchen.recipe', verbose_name='Recette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Lot de préparation',
                'verbose_name_plural': 'Lots de préparation',
                'ordering': ['-created_at'],
            },
        ),
    ]
