# Generated by Django 4.2.7 on 2025-08-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('kitchen', '0003_recipepreparationbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_ingredients', to='suppliers.supplier', verbose_name='Fournisseur principal'),
        ),
    ]
