# Generated by Django 4.2.7 on 2025-08-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_table_last_cleaned_table_notes_table_occupied_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Client/Réservation'),
        ),
        migrations.AddField(
            model_name='table',
            name='server',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serveur assigné'),
        ),
    ]
