# Generated by Django 4.2.7 on 2025-08-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('beverages', 'Boissons'), ('food', 'Produits alimentaires'), ('ingredients', 'Ingrédients pour recettes'), ('equipment', 'Équipements'), ('cleaning', "Produits d'entretien"), ('other', 'Autres')], default='other', max_length=20, verbose_name='Type de fournisseur'),
        ),
    ]
